In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
#Mean Absolute Error
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [3]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [4]:
#implementing using numpy
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [5]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [6]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

mae_np(y_predicted, y_true)

0.5

In [7]:
#Log Loss or Binary Cross Entropy
epsilon = 1e-15

In [9]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
print(y_predicted)
print(y_predicted_new)

[1 1 0 0 1]
[1, 1, 1e-15, 1e-15, 1]


In [10]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [12]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [13]:
#formula
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [14]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [15]:
log_loss(y_true, y_predicted)

17.2696280766844

In [16]:
#Mean Sqaured error

def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [17]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

In [18]:
#using numpy
np.mean(np.square(y_true-y_predicted))

0.366